// Control plane for mod_open_switch.
//
// Callers (orchestrators, bots, agents) invoke these RPCs to drive
// FreeSWITCH from outside. The module exposes this service in-process so
// no extra hop is required.
//
// Idempotency: write methods are idempotent when `request_id` is
// supplied. The module's per-process LRU cache (default TTL 300s)
// returns the cached response — success OR error — for duplicate
// `(tenant_id, request_id)` within the window. While the original
// is in flight, retries block on an in-flight marker with a shadow
// deadline = min(gRPC deadline, idempotency_in_flight_max_wait).
// See openspec/changes/core-module-v1/specs/control-api/spec.md
// §Idempotency for the full semantics including error-cache
// behaviour, configuration knobs, and the module-restart gap.
//
// Stability: v1 is unstable until 1.0.0 ships. Breaking changes will bump
// the version path (e.g. /v2).

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.34.0
// source: open_switch/control/v1/control.proto

package v1

import (
	context "context"
	v1 "github.com/luongdev/open-switch/examples/go-client/pb/open_switch/events/v1"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ControlService_Originate_FullMethodName       = "/open_switch.control.v1.ControlService/Originate"
	ControlService_Hangup_FullMethodName          = "/open_switch.control.v1.ControlService/Hangup"
	ControlService_HangupMany_FullMethodName      = "/open_switch.control.v1.ControlService/HangupMany"
	ControlService_Bridge_FullMethodName          = "/open_switch.control.v1.ControlService/Bridge"
	ControlService_Execute_FullMethodName         = "/open_switch.control.v1.ControlService/Execute"
	ControlService_SetVariables_FullMethodName    = "/open_switch.control.v1.ControlService/SetVariables"
	ControlService_Hold_FullMethodName            = "/open_switch.control.v1.ControlService/Hold"
	ControlService_Unhold_FullMethodName          = "/open_switch.control.v1.ControlService/Unhold"
	ControlService_BlindTransfer_FullMethodName   = "/open_switch.control.v1.ControlService/BlindTransfer"
	ControlService_SubscribeEvents_FullMethodName = "/open_switch.control.v1.ControlService/SubscribeEvents"
	ControlService_Health_FullMethodName          = "/open_switch.control.v1.ControlService/Health"
)

// ControlServiceClient is the client API for ControlService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ControlServiceClient interface {
	// Originate a new call. Returns the channel UUID once the call is
	// routed (not necessarily answered).
	Originate(ctx context.Context, in *OriginateRequest, opts ...grpc.CallOption) (*OriginateResponse, error)
	// Hang up a single channel by UUID with a cause code.
	Hangup(ctx context.Context, in *HangupRequest, opts ...grpc.CallOption) (*HangupResponse, error)
	// Hang up many channels at once (rare; use for tenant-wide drain).
	HangupMany(ctx context.Context, in *HangupManyRequest, opts ...grpc.CallOption) (*HangupManyResponse, error)
	// Bridge two existing legs by UUID.
	Bridge(ctx context.Context, in *BridgeRequest, opts ...grpc.CallOption) (*BridgeResponse, error)
	// Execute a FreeSWITCH dialplan application on a channel.
	Execute(ctx context.Context, in *ExecuteRequest, opts ...grpc.CallOption) (*ExecuteResponse, error)
	// Set channel variables.
	SetVariables(ctx context.Context, in *SetVariablesRequest, opts ...grpc.CallOption) (*SetVariablesResponse, error)
	// Hold / unhold a channel.
	Hold(ctx context.Context, in *HoldRequest, opts ...grpc.CallOption) (*HoldResponse, error)
	Unhold(ctx context.Context, in *UnholdRequest, opts ...grpc.CallOption) (*UnholdResponse, error)
	// Blind transfer a channel to a destination.
	BlindTransfer(ctx context.Context, in *BlindTransferRequest, opts ...grpc.CallOption) (*BlindTransferResponse, error)
	// Subscribe to events via gRPC server-streaming. THIS IS THE SOLE
	// EVENT TRANSPORT. The module delivers events to all active subscribers
	// from its in-memory per-tier replay rings; subscribers persist to
	// durable storage on their own side (Kafka / Redis / S3 / file / etc.).
	//
	// For Tier-1 (billing-grade) no-loss requirements, operators MUST run
	// ≥ 2 subscribers per node in HA — see event-tiers.md §"No-loss
	// reference architecture". Slow subscribers are kicked with
	// RESOURCE_EXHAUSTED when their per-subscriber send queue overflows.
	SubscribeEvents(ctx context.Context, in *SubscribeEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[v1.EventEnvelope], error)
	// Health + module status.
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
}

type controlServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewControlServiceClient(cc grpc.ClientConnInterface) ControlServiceClient {
	return &controlServiceClient{cc}
}

func (c *controlServiceClient) Originate(ctx context.Context, in *OriginateRequest, opts ...grpc.CallOption) (*OriginateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OriginateResponse)
	err := c.cc.Invoke(ctx, ControlService_Originate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlServiceClient) Hangup(ctx context.Context, in *HangupRequest, opts ...grpc.CallOption) (*HangupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HangupResponse)
	err := c.cc.Invoke(ctx, ControlService_Hangup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlServiceClient) HangupMany(ctx context.Context, in *HangupManyRequest, opts ...grpc.CallOption) (*HangupManyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HangupManyResponse)
	err := c.cc.Invoke(ctx, ControlService_HangupMany_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlServiceClient) Bridge(ctx context.Context, in *BridgeRequest, opts ...grpc.CallOption) (*BridgeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BridgeResponse)
	err := c.cc.Invoke(ctx, ControlService_Bridge_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlServiceClient) Execute(ctx context.Context, in *ExecuteRequest, opts ...grpc.CallOption) (*ExecuteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecuteResponse)
	err := c.cc.Invoke(ctx, ControlService_Execute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlServiceClient) SetVariables(ctx context.Context, in *SetVariablesRequest, opts ...grpc.CallOption) (*SetVariablesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetVariablesResponse)
	err := c.cc.Invoke(ctx, ControlService_SetVariables_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlServiceClient) Hold(ctx context.Context, in *HoldRequest, opts ...grpc.CallOption) (*HoldResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HoldResponse)
	err := c.cc.Invoke(ctx, ControlService_Hold_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlServiceClient) Unhold(ctx context.Context, in *UnholdRequest, opts ...grpc.CallOption) (*UnholdResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnholdResponse)
	err := c.cc.Invoke(ctx, ControlService_Unhold_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlServiceClient) BlindTransfer(ctx context.Context, in *BlindTransferRequest, opts ...grpc.CallOption) (*BlindTransferResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BlindTransferResponse)
	err := c.cc.Invoke(ctx, ControlService_BlindTransfer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlServiceClient) SubscribeEvents(ctx context.Context, in *SubscribeEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[v1.EventEnvelope], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ControlService_ServiceDesc.Streams[0], ControlService_SubscribeEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeEventsRequest, v1.EventEnvelope]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ControlService_SubscribeEventsClient = grpc.ServerStreamingClient[v1.EventEnvelope]

func (c *controlServiceClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, ControlService_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ControlServiceServer is the server API for ControlService service.
// All implementations must embed UnimplementedControlServiceServer
// for forward compatibility.
type ControlServiceServer interface {
	// Originate a new call. Returns the channel UUID once the call is
	// routed (not necessarily answered).
	Originate(context.Context, *OriginateRequest) (*OriginateResponse, error)
	// Hang up a single channel by UUID with a cause code.
	Hangup(context.Context, *HangupRequest) (*HangupResponse, error)
	// Hang up many channels at once (rare; use for tenant-wide drain).
	HangupMany(context.Context, *HangupManyRequest) (*HangupManyResponse, error)
	// Bridge two existing legs by UUID.
	Bridge(context.Context, *BridgeRequest) (*BridgeResponse, error)
	// Execute a FreeSWITCH dialplan application on a channel.
	Execute(context.Context, *ExecuteRequest) (*ExecuteResponse, error)
	// Set channel variables.
	SetVariables(context.Context, *SetVariablesRequest) (*SetVariablesResponse, error)
	// Hold / unhold a channel.
	Hold(context.Context, *HoldRequest) (*HoldResponse, error)
	Unhold(context.Context, *UnholdRequest) (*UnholdResponse, error)
	// Blind transfer a channel to a destination.
	BlindTransfer(context.Context, *BlindTransferRequest) (*BlindTransferResponse, error)
	// Subscribe to events via gRPC server-streaming. THIS IS THE SOLE
	// EVENT TRANSPORT. The module delivers events to all active subscribers
	// from its in-memory per-tier replay rings; subscribers persist to
	// durable storage on their own side (Kafka / Redis / S3 / file / etc.).
	//
	// For Tier-1 (billing-grade) no-loss requirements, operators MUST run
	// ≥ 2 subscribers per node in HA — see event-tiers.md §"No-loss
	// reference architecture". Slow subscribers are kicked with
	// RESOURCE_EXHAUSTED when their per-subscriber send queue overflows.
	SubscribeEvents(*SubscribeEventsRequest, grpc.ServerStreamingServer[v1.EventEnvelope]) error
	// Health + module status.
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	mustEmbedUnimplementedControlServiceServer()
}

// UnimplementedControlServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedControlServiceServer struct{}

func (UnimplementedControlServiceServer) Originate(context.Context, *OriginateRequest) (*OriginateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Originate not implemented")
}
func (UnimplementedControlServiceServer) Hangup(context.Context, *HangupRequest) (*HangupResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Hangup not implemented")
}
func (UnimplementedControlServiceServer) HangupMany(context.Context, *HangupManyRequest) (*HangupManyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HangupMany not implemented")
}
func (UnimplementedControlServiceServer) Bridge(context.Context, *BridgeRequest) (*BridgeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Bridge not implemented")
}
func (UnimplementedControlServiceServer) Execute(context.Context, *ExecuteRequest) (*ExecuteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Execute not implemented")
}
func (UnimplementedControlServiceServer) SetVariables(context.Context, *SetVariablesRequest) (*SetVariablesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetVariables not implemented")
}
func (UnimplementedControlServiceServer) Hold(context.Context, *HoldRequest) (*HoldResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Hold not implemented")
}
func (UnimplementedControlServiceServer) Unhold(context.Context, *UnholdRequest) (*UnholdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Unhold not implemented")
}
func (UnimplementedControlServiceServer) BlindTransfer(context.Context, *BlindTransferRequest) (*BlindTransferResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BlindTransfer not implemented")
}
func (UnimplementedControlServiceServer) SubscribeEvents(*SubscribeEventsRequest, grpc.ServerStreamingServer[v1.EventEnvelope]) error {
	return status.Errorf(codes.Unimplemented, "method SubscribeEvents not implemented")
}
func (UnimplementedControlServiceServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedControlServiceServer) mustEmbedUnimplementedControlServiceServer() {}
func (UnimplementedControlServiceServer) testEmbeddedByValue()                        {}

// UnsafeControlServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ControlServiceServer will
// result in compilation errors.
type UnsafeControlServiceServer interface {
	mustEmbedUnimplementedControlServiceServer()
}

func RegisterControlServiceServer(s grpc.ServiceRegistrar, srv ControlServiceServer) {
	// If the following call pancis, it indicates UnimplementedControlServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ControlService_ServiceDesc, srv)
}

func _ControlService_Originate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OriginateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).Originate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlService_Originate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).Originate(ctx, req.(*OriginateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlService_Hangup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HangupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).Hangup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlService_Hangup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).Hangup(ctx, req.(*HangupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlService_HangupMany_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HangupManyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).HangupMany(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlService_HangupMany_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).HangupMany(ctx, req.(*HangupManyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlService_Bridge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BridgeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).Bridge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlService_Bridge_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).Bridge(ctx, req.(*BridgeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlService_Execute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).Execute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlService_Execute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).Execute(ctx, req.(*ExecuteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlService_SetVariables_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetVariablesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).SetVariables(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlService_SetVariables_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).SetVariables(ctx, req.(*SetVariablesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlService_Hold_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HoldRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).Hold(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlService_Hold_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).Hold(ctx, req.(*HoldRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlService_Unhold_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnholdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).Unhold(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlService_Unhold_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).Unhold(ctx, req.(*UnholdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlService_BlindTransfer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BlindTransferRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).BlindTransfer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlService_BlindTransfer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).BlindTransfer(ctx, req.(*BlindTransferRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlService_SubscribeEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeEventsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ControlServiceServer).SubscribeEvents(m, &grpc.GenericServerStream[SubscribeEventsRequest, v1.EventEnvelope]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ControlService_SubscribeEventsServer = grpc.ServerStreamingServer[v1.EventEnvelope]

func _ControlService_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlService_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ControlService_ServiceDesc is the grpc.ServiceDesc for ControlService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ControlService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "open_switch.control.v1.ControlService",
	HandlerType: (*ControlServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Originate",
			Handler:    _ControlService_Originate_Handler,
		},
		{
			MethodName: "Hangup",
			Handler:    _ControlService_Hangup_Handler,
		},
		{
			MethodName: "HangupMany",
			Handler:    _ControlService_HangupMany_Handler,
		},
		{
			MethodName: "Bridge",
			Handler:    _ControlService_Bridge_Handler,
		},
		{
			MethodName: "Execute",
			Handler:    _ControlService_Execute_Handler,
		},
		{
			MethodName: "SetVariables",
			Handler:    _ControlService_SetVariables_Handler,
		},
		{
			MethodName: "Hold",
			Handler:    _ControlService_Hold_Handler,
		},
		{
			MethodName: "Unhold",
			Handler:    _ControlService_Unhold_Handler,
		},
		{
			MethodName: "BlindTransfer",
			Handler:    _ControlService_BlindTransfer_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _ControlService_Health_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribeEvents",
			Handler:       _ControlService_SubscribeEvents_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "open_switch/control/v1/control.proto",
}
