/*
 * src/control/call_cause.cc
 *
 * osw::control::CallCause — two-way mapping between proto cause strings
 * and switch_call_cause_t (Q.850-derived).
 *
 * In the production build this could delegate to FS's own
 * switch_channel_cause2str / switch_channel_str2cause. We do NOT do
 * that because (a) those symbols are only available in the production
 * libfreeswitch.so — unit tests use the FS-mock seam without that
 * library, and (b) a self-contained table lets us surface the exact
 * subset the proto documents, making regressions visible in code
 * review rather than silently deferred to link time.
 *
 * The table covers every SWITCH_CAUSE_* value defined in v1.10.12's
 * switch_types.h and mirrors the string names produced by FS's own
 * CAUSE_CHART (src/switch_channel.c). Verified at v1.10.12 — see
 * FREESWITCH-FACTS FF-022.
 *
 * SPDX-License-Identifier: AGPL-3.0-or-later
 */

#include "osw/control/call_cause.h"

#include <array>
#include <cstring>

namespace osw::control {

namespace {

struct CauseEntry {
    switch_call_cause_t value;
    const char* name;  // NUL-terminated; lifetime = program
};

// FF-022: table matches FS CAUSE_CHART in src/switch_channel.c at
// v1.10.12. String names are all-caps, no "SWITCH_CAUSE_" prefix —
// that matches the FS convention and what operators put in HangupRequest.
//
// NOLINTBEGIN(cppcoreguidelines-avoid-magic-numbers)
constexpr std::array<CauseEntry, 82> kCauseTable{{
    {SWITCH_CAUSE_NONE, "NONE"},
    {SWITCH_CAUSE_UNALLOCATED_NUMBER, "UNALLOCATED_NUMBER"},
    {SWITCH_CAUSE_NO_ROUTE_TRANSIT_NET, "NO_ROUTE_TRANSIT_NET"},
    {SWITCH_CAUSE_NO_ROUTE_DESTINATION, "NO_ROUTE_DESTINATION"},
    {SWITCH_CAUSE_CHANNEL_UNACCEPTABLE, "CHANNEL_UNACCEPTABLE"},
    {SWITCH_CAUSE_CALL_AWARDED_DELIVERED, "CALL_AWARDED_DELIVERED"},
    {SWITCH_CAUSE_NORMAL_CLEARING, "NORMAL_CLEARING"},
    {SWITCH_CAUSE_USER_BUSY, "USER_BUSY"},
    {SWITCH_CAUSE_NO_USER_RESPONSE, "NO_USER_RESPONSE"},
    {SWITCH_CAUSE_NO_ANSWER, "NO_ANSWER"},
    {SWITCH_CAUSE_SUBSCRIBER_ABSENT, "SUBSCRIBER_ABSENT"},
    {SWITCH_CAUSE_CALL_REJECTED, "CALL_REJECTED"},
    {SWITCH_CAUSE_NUMBER_CHANGED, "NUMBER_CHANGED"},
    {SWITCH_CAUSE_REDIRECTION_TO_NEW_DESTINATION, "REDIRECTION_TO_NEW_DESTINATION"},
    {SWITCH_CAUSE_EXCHANGE_ROUTING_ERROR, "EXCHANGE_ROUTING_ERROR"},
    {SWITCH_CAUSE_DESTINATION_OUT_OF_ORDER, "DESTINATION_OUT_OF_ORDER"},
    {SWITCH_CAUSE_INVALID_NUMBER_FORMAT, "INVALID_NUMBER_FORMAT"},
    {SWITCH_CAUSE_FACILITY_REJECTED, "FACILITY_REJECTED"},
    {SWITCH_CAUSE_RESPONSE_TO_STATUS_ENQUIRY, "RESPONSE_TO_STATUS_ENQUIRY"},
    {SWITCH_CAUSE_NORMAL_UNSPECIFIED, "NORMAL_UNSPECIFIED"},
    {SWITCH_CAUSE_NORMAL_CIRCUIT_CONGESTION, "NORMAL_CIRCUIT_CONGESTION"},
    {SWITCH_CAUSE_NETWORK_OUT_OF_ORDER, "NETWORK_OUT_OF_ORDER"},
    {SWITCH_CAUSE_NORMAL_TEMPORARY_FAILURE, "NORMAL_TEMPORARY_FAILURE"},
    {SWITCH_CAUSE_SWITCH_CONGESTION, "SWITCH_CONGESTION"},
    {SWITCH_CAUSE_ACCESS_INFO_DISCARDED, "ACCESS_INFO_DISCARDED"},
    {SWITCH_CAUSE_REQUESTED_CHAN_UNAVAIL, "REQUESTED_CHAN_UNAVAIL"},
    {SWITCH_CAUSE_PRE_EMPTED, "PRE_EMPTED"},
    {SWITCH_CAUSE_FACILITY_NOT_SUBSCRIBED, "FACILITY_NOT_SUBSCRIBED"},
    {SWITCH_CAUSE_OUTGOING_CALL_BARRED, "OUTGOING_CALL_BARRED"},
    {SWITCH_CAUSE_INCOMING_CALL_BARRED, "INCOMING_CALL_BARRED"},
    {SWITCH_CAUSE_BEARERCAPABILITY_NOTAUTH, "BEARERCAPABILITY_NOTAUTH"},
    {SWITCH_CAUSE_BEARERCAPABILITY_NOTAVAIL, "BEARERCAPABILITY_NOTAVAIL"},
    {SWITCH_CAUSE_SERVICE_UNAVAILABLE, "SERVICE_UNAVAILABLE"},
    {SWITCH_CAUSE_BEARERCAPABILITY_NOTIMPL, "BEARERCAPABILITY_NOTIMPL"},
    {SWITCH_CAUSE_CHAN_NOT_IMPLEMENTED, "CHAN_NOT_IMPLEMENTED"},
    {SWITCH_CAUSE_FACILITY_NOT_IMPLEMENTED, "FACILITY_NOT_IMPLEMENTED"},
    {SWITCH_CAUSE_SERVICE_NOT_IMPLEMENTED, "SERVICE_NOT_IMPLEMENTED"},
    {SWITCH_CAUSE_INVALID_CALL_REFERENCE, "INVALID_CALL_REFERENCE"},
    {SWITCH_CAUSE_INCOMPATIBLE_DESTINATION, "INCOMPATIBLE_DESTINATION"},
    {SWITCH_CAUSE_INVALID_MSG_UNSPECIFIED, "INVALID_MSG_UNSPECIFIED"},
    {SWITCH_CAUSE_MANDATORY_IE_MISSING, "MANDATORY_IE_MISSING"},
    {SWITCH_CAUSE_MESSAGE_TYPE_NONEXIST, "MESSAGE_TYPE_NONEXIST"},
    {SWITCH_CAUSE_WRONG_MESSAGE, "WRONG_MESSAGE"},
    {SWITCH_CAUSE_IE_NONEXIST, "IE_NONEXIST"},
    {SWITCH_CAUSE_INVALID_IE_CONTENTS, "INVALID_IE_CONTENTS"},
    {SWITCH_CAUSE_WRONG_CALL_STATE, "WRONG_CALL_STATE"},
    {SWITCH_CAUSE_RECOVERY_ON_TIMER_EXPIRE, "RECOVERY_ON_TIMER_EXPIRE"},
    {SWITCH_CAUSE_MANDATORY_IE_LENGTH_ERROR, "MANDATORY_IE_LENGTH_ERROR"},
    {SWITCH_CAUSE_PROTOCOL_ERROR, "PROTOCOL_ERROR"},
    {SWITCH_CAUSE_INTERWORKING, "INTERWORKING"},
    {SWITCH_CAUSE_SUCCESS, "SUCCESS"},
    {SWITCH_CAUSE_ORIGINATOR_CANCEL, "ORIGINATOR_CANCEL"},
    {SWITCH_CAUSE_CRASH, "CRASH"},
    {SWITCH_CAUSE_SYSTEM_SHUTDOWN, "SYSTEM_SHUTDOWN"},
    {SWITCH_CAUSE_LOSE_RACE, "LOSE_RACE"},
    {SWITCH_CAUSE_MANAGER_REQUEST, "MANAGER_REQUEST"},
    {SWITCH_CAUSE_BLIND_TRANSFER, "BLIND_TRANSFER"},
    {SWITCH_CAUSE_ATTENDED_TRANSFER, "ATTENDED_TRANSFER"},
    {SWITCH_CAUSE_ALLOTTED_TIMEOUT, "ALLOTTED_TIMEOUT"},
    {SWITCH_CAUSE_USER_CHALLENGE, "USER_CHALLENGE"},
    {SWITCH_CAUSE_MEDIA_TIMEOUT, "MEDIA_TIMEOUT"},
    {SWITCH_CAUSE_PICKED_OFF, "PICKED_OFF"},
    {SWITCH_CAUSE_USER_NOT_REGISTERED, "USER_NOT_REGISTERED"},
    {SWITCH_CAUSE_PROGRESS_TIMEOUT, "PROGRESS_TIMEOUT"},
    {SWITCH_CAUSE_INVALID_GATEWAY, "INVALID_GATEWAY"},
    {SWITCH_CAUSE_GATEWAY_DOWN, "GATEWAY_DOWN"},
    {SWITCH_CAUSE_INVALID_URL, "INVALID_URL"},
    {SWITCH_CAUSE_INVALID_PROFILE, "INVALID_PROFILE"},
    {SWITCH_CAUSE_NO_PICKUP, "NO_PICKUP"},
    {SWITCH_CAUSE_SRTP_READ_ERROR, "SRTP_READ_ERROR"},
    {SWITCH_CAUSE_BOWOUT, "BOWOUT"},
    {SWITCH_CAUSE_BUSY_EVERYWHERE, "BUSY_EVERYWHERE"},
    {SWITCH_CAUSE_DECLINE, "DECLINE"},
    {SWITCH_CAUSE_DOES_NOT_EXIST_ANYWHERE, "DOES_NOT_EXIST_ANYWHERE"},
    {SWITCH_CAUSE_NOT_ACCEPTABLE, "NOT_ACCEPTABLE"},
    {SWITCH_CAUSE_UNWANTED, "UNWANTED"},
    {SWITCH_CAUSE_NO_IDENTITY, "NO_IDENTITY"},
    {SWITCH_CAUSE_BAD_IDENTITY_INFO, "BAD_IDENTITY_INFO"},
    {SWITCH_CAUSE_UNSUPPORTED_CERTIFICATE, "UNSUPPORTED_CERTIFICATE"},
    {SWITCH_CAUSE_INVALID_IDENTITY, "INVALID_IDENTITY"},
    {SWITCH_CAUSE_STALE_DATE, "STALE_DATE"},
    {SWITCH_CAUSE_REJECT_ALL, "REJECT_ALL"},
}};
// NOLINTEND(cppcoreguidelines-avoid-magic-numbers)

}  // namespace

// static
switch_call_cause_t CallCause::FromString(std::string_view cause_str) noexcept {
    if (cause_str.empty() || cause_str == "UNSPECIFIED") {
        return SWITCH_CAUSE_NORMAL_CLEARING;
    }
    for (const auto& entry : kCauseTable) {
        if (cause_str == entry.name) {
            return entry.value;
        }
    }
    return SWITCH_CAUSE_NORMAL_CLEARING;
}

// static
std::string_view CallCause::ToString(switch_call_cause_t cause) noexcept {
    for (const auto& entry : kCauseTable) {
        if (entry.value == cause) {
            return entry.name;
        }
    }
    return "UNSPECIFIED";
}

}  // namespace osw::control
