// Media plane for mod_open_switch.
//
// Per-call bidirectional audio streams from FreeSWITCH (via media bug) to
// an external service: TTS, STT, voicebot, AMD, etc. The module is the
// gRPC CLIENT here (it initiates the stream); the external service is the
// SERVER.
//
// Design:
//   - One stream per (channel_uuid, purpose) pair. A single call may have
//     several streams open simultaneously (e.g. STT + TTS + recording-relay).
//   - The first client→server message MUST be a StreamStart; subsequent
//     messages are AudioFrame. The first server→client message is
//     StreamReady; subsequent messages are AudioFrame or Control.
//   - Cancellation is propagated bidirectionally: gRPC cancel on either
//     side -> media bug removed and call audio falls back to silence.
//   - On call hangup, the module half-closes the client send stream and
//     waits up to `drain_timeout_ms` for the server to finish before
//     forcibly cancelling.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: open_switch/media/v1/media.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MediaBridge_Stream_FullMethodName = "/open_switch.media.v1.MediaBridge/Stream"
)

// MediaBridgeClient is the client API for MediaBridge service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// MediaBridge is implemented by EXTERNAL services (TTS, STT, voicebot, ...).
// The module is the client. The module opens one stream per (call, purpose)
// tuple.
type MediaBridgeClient interface {
	Stream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[FromModule, FromService], error)
}

type mediaBridgeClient struct {
	cc grpc.ClientConnInterface
}

func NewMediaBridgeClient(cc grpc.ClientConnInterface) MediaBridgeClient {
	return &mediaBridgeClient{cc}
}

func (c *mediaBridgeClient) Stream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[FromModule, FromService], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MediaBridge_ServiceDesc.Streams[0], MediaBridge_Stream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[FromModule, FromService]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MediaBridge_StreamClient = grpc.BidiStreamingClient[FromModule, FromService]

// MediaBridgeServer is the server API for MediaBridge service.
// All implementations must embed UnimplementedMediaBridgeServer
// for forward compatibility.
//
// MediaBridge is implemented by EXTERNAL services (TTS, STT, voicebot, ...).
// The module is the client. The module opens one stream per (call, purpose)
// tuple.
type MediaBridgeServer interface {
	Stream(grpc.BidiStreamingServer[FromModule, FromService]) error
	mustEmbedUnimplementedMediaBridgeServer()
}

// UnimplementedMediaBridgeServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMediaBridgeServer struct{}

func (UnimplementedMediaBridgeServer) Stream(grpc.BidiStreamingServer[FromModule, FromService]) error {
	return status.Errorf(codes.Unimplemented, "method Stream not implemented")
}
func (UnimplementedMediaBridgeServer) mustEmbedUnimplementedMediaBridgeServer() {}
func (UnimplementedMediaBridgeServer) testEmbeddedByValue()                     {}

// UnsafeMediaBridgeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MediaBridgeServer will
// result in compilation errors.
type UnsafeMediaBridgeServer interface {
	mustEmbedUnimplementedMediaBridgeServer()
}

func RegisterMediaBridgeServer(s grpc.ServiceRegistrar, srv MediaBridgeServer) {
	// If the following call pancis, it indicates UnimplementedMediaBridgeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MediaBridge_ServiceDesc, srv)
}

func _MediaBridge_Stream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MediaBridgeServer).Stream(&grpc.GenericServerStream[FromModule, FromService]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MediaBridge_StreamServer = grpc.BidiStreamingServer[FromModule, FromService]

// MediaBridge_ServiceDesc is the grpc.ServiceDesc for MediaBridge service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MediaBridge_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "open_switch.media.v1.MediaBridge",
	HandlerType: (*MediaBridgeServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Stream",
			Handler:       _MediaBridge_Stream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "open_switch/media/v1/media.proto",
}
